---
abstract: 'Perl Framework for authoring Juju charms'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires:
  App::Prove: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  FindBin: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  IPC::System::Simple: '0'
  Pod::Elemental::Transformer::List: '0'
  Software::License: '0'
  Test::Compile: '0'
  Test::Kwalitee: '0'
  Test::More: '0'
  autodie: '0'
  lib: '0'
  perl: '5.006'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-CharmKit
no_index:
  directory:
    - 't xt eg share'
requires:
  App::Cmd::Setup: '0'
  Class::Tiny: '0'
  Config::Tiny: '0'
  Data::Dumper: '0'
  Data::Faker: '0'
  Email::Address: '0'
  English: '0'
  Exporter::Tiny: '0'
  File::ShareDir: '0'
  File::chdir: '0'
  Git::Repository: '0'
  HTTP::Tiny: '0'
  IO::Prompter: '0'
  IO::Socket::PortState: '0'
  IPC::Run: '0'
  Import::Into: '0'
  JSON::PP: '0'
  Juju: '0'
  Module::Runtime: '0'
  Params::Util: '0'
  Path::Tiny: '0'
  Set::Tiny: '0'
  Software::License: '0'
  Test::Exception: '0'
  Test::More: '0'
  Text::MicroTemplate: '0'
  YAML::Tiny: '0'
  base: '0'
  boolean: '0'
  feature: '0'
  parent: '0'
  strict: '0'
  utf8::all: '0'
  warnings: '0'
resources:
  repository: git://github.com/battlemidget/App-CharmKit.git
version: 1.0.6
x_author_pledge:
  version: 1
