=head1 CharmKit Resources

* L<https://jujucharms.com/docs/>
Juju documentation to learn more about Juju and Charms.

=head1 Manual

* L<App::CharmKit::Manual::GettingStarted>
Brief walkthrough on getting started with L<App::CharmKit>
* L<App::CharmKit::Manual::WritingHooks>
Help on writing hooks using CharmKit.

=cut
