# PODNAME: Manual

=head1 CharmKit Resources

=over

=item L<https://jujucharms.com/docs/>

Juju documentation to learn more about Juju and Charms.

=back

=head1 Manual

=over

=item L<App::CharmKit::Manual::GettingStarted>

Brief walkthrough on getting started with L<App::CharmKit>

=item L<App::CharmKit::Manual::WritingHooks>

Help on writing hooks using CharmKit.

=back

=cut
